const STORAGE_KEY='jinjiSoftwareDataV1';
let data=loadData();
const $=id=>document.getElementById(id);
const pages={dashboard:'ダッシュボード','employee-form':'社員登録',employees:'社員一覧',leave:'有給管理','entry-exit':'入社・退社登録',retirees:'退職者一覧',ledger:'労働者名簿',settings:'データ管理'};
function loadData(){try{return JSON.parse(localStorage.getItem(STORAGE_KEY))||{employees:[],leaves:[]}}catch{return{employees:[],leaves:[]}}}
function saveData(){localStorage.setItem(STORAGE_KEY,JSON.stringify(data));renderAll()}
function esc(v=''){return String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function fmt(d){if(!d)return'-';const [y,m,day]=d.split('-');return `${y}/${m}/${day}`}
function uid(){return crypto.randomUUID?crypto.randomUUID():Date.now().toString(36)+Math.random().toString(36).slice(2)}
function toast(msg){const t=$('toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2300)}
function activeEmployees(){return data.employees.filter(e=>!e.retireDate)}
function leaveBalance(id){return data.leaves.filter(l=>l.employeeId===id).reduce((n,l)=>n+(l.type==='take'?-Number(l.days):Number(l.days)),0)}
function showPage(id){document.querySelectorAll('.page').forEach(p=>p.classList.toggle('active',p.id===id));document.querySelectorAll('#nav button').forEach(b=>b.classList.toggle('active',b.dataset.page===id));$('pageTitle').textContent=pages[id];document.querySelector('.sidebar').classList.remove('open');if(id==='ledger')renderLedger();window.scrollTo(0,0)}
document.querySelectorAll('[data-page]').forEach(b=>b.onclick=()=>showPage(b.dataset.page));document.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>showPage(b.dataset.go));$('menuBtn').onclick=()=>document.querySelector('.sidebar').classList.toggle('open');
$('today').textContent=new Intl.DateTimeFormat('ja-JP',{year:'numeric',month:'long',day:'numeric',weekday:'long'}).format(new Date());
function employeeFromForm(){return{id:$('employeeId').value||uid(),employeeNo:$('employeeNo').value.trim(),name:$('name').value.trim(),kana:$('kana').value.trim(),birthDate:$('birthDate').value,gender:$('gender').value,myNumber:$('myNumber').value.trim(),hireDate:$('hireDate').value,department:$('department').value.trim(),position:$('position').value.trim(),employmentType:$('employmentType').value,weeklyDays:$('weeklyDays').value,dailyHours:$('dailyHours').value,postalCode:$('postalCode').value.trim(),address:$('address').value.trim(),phone:$('phone').value.trim(),email:$('email').value.trim(),emergencyName:$('emergencyName').value.trim(),emergencyPhone:$('emergencyPhone').value.trim(),pensionNo:$('pensionNo').value.trim(),employmentInsuranceNo:$('employmentInsuranceNo').value.trim(),healthInsuranceNo:$('healthInsuranceNo').value.trim(),notes:$('notes').value.trim()}}
$('employeeForm').onsubmit=e=>{e.preventDefault();const item=employeeFromForm();if(data.employees.some(x=>x.employeeNo===item.employeeNo&&x.id!==item.id)){toast('同じ社員番号が登録されています');return}const old=data.employees.find(x=>x.id===item.id);if(old)Object.assign(old,item);else data.employees.push(item);saveData();resetEmployeeForm();showPage('employees');toast(old?'社員情報を更新しました':'社員を登録しました')};
function resetEmployeeForm(){$('employeeForm').reset();$('employeeId').value='';$('weeklyDays').value=5;$('dailyHours').value=8;$('employeeFormTitle').textContent='社員登録'}$('resetEmployee').onclick=resetEmployeeForm;
function editEmployee(id){const e=data.employees.find(x=>x.id===id);if(!e)return;Object.keys(e).forEach(k=>{if($(k))$(k).value=e[k]??''});$('employeeFormTitle').textContent='社員情報を編集';showPage('employee-form')}
function deleteEmployee(id){if(!confirm('この社員と有給履歴を削除しますか？'))return;data.employees=data.employees.filter(e=>e.id!==id);data.leaves=data.leaves.filter(l=>l.employeeId!==id);saveData();toast('削除しました')}
function restoreEmployee(id){const e=data.employees.find(x=>x.id===id);if(!e||!confirm(`${e.name}さんを在籍社員に戻しますか？`))return;delete e.retireDate;delete e.retireReason;delete e.retireNote;saveData();toast('在籍社員に戻しました')}
function renderDashboard(){const active=activeEmployees(),now=new Date(),ym=now.toISOString().slice(0,7);$('statActive').textContent=active.length;$('statJoined').textContent=active.filter(e=>e.hireDate?.startsWith(ym)).length;$('statRetired').textContent=data.employees.filter(e=>e.retireDate?.startsWith(ym)).length;$('statLeave').textContent=active.reduce((n,e)=>n+leaveBalance(e.id),0).toFixed(1).replace('.0','');$('recentEmployees').innerHTML=active.length?`<div class="mini-list">${active.slice(-5).reverse().map(e=>`<div class="mini-row"><span><b>${esc(e.name)}</b>　${esc(e.department||'所属未設定')}</span><span>${fmt(e.hireDate)} 入社</span></div>`).join('')}</div>`:'社員が登録されていません';const alerts=[];active.forEach(e=>{const b=leaveBalance(e.id);if(b<0)alerts.push(`${esc(e.name)}さんの有給残日数がマイナスです（${b}日）`)});$('alerts').innerHTML=alerts.length?alerts.map(a=>`<div class="notice">${a}</div>`).join(''):'現在のお知らせはありません'}
function renderEmployees(){const q=$('employeeSearch').value.toLowerCase(),dep=$('departmentFilter').value;const list=activeEmployees().filter(e=>(!q||[e.name,e.kana,e.employeeNo,e.department].some(v=>(v||'').toLowerCase().includes(q)))&&(!dep||e.department===dep));$('employeeRows').innerHTML=list.length?list.map(e=>`<tr><td>${esc(e.employeeNo)}</td><td><b>${esc(e.name)}</b><br><small>${esc(e.kana)}</small></td><td>${esc(e.department||'-')}</td><td><span class="badge">${esc(e.employmentType)}</span></td><td>${fmt(e.hireDate)}</td><td>${leaveBalance(e.id).toFixed(1).replace('.0','')}日</td><td><div class="table-actions"><button class="icon-btn" onclick="editEmployee('${e.id}')">編集</button><button class="icon-btn" onclick="selectLedger('${e.id}')">名簿</button><button class="icon-btn" onclick="deleteEmployee('${e.id}')">削除</button></div></td></tr>`).join(''):'<tr><td class="empty-cell" colspan="7">該当する社員はいません</td></tr>';const deps=[...new Set(activeEmployees().map(e=>e.department).filter(Boolean))].sort();const current=$('departmentFilter').value;$('departmentFilter').innerHTML='<option value="">すべての部署</option>'+deps.map(d=>`<option ${d===current?'selected':''}>${esc(d)}</option>`).join('')}
$('employeeSearch').oninput=renderEmployees;$('departmentFilter').onchange=renderEmployees;
$('leaveForm').onsubmit=e=>{e.preventDefault();data.leaves.push({id:uid(),employeeId:$('leaveEmployee').value,type:$('leaveType').value,date:$('leaveDate').value,days:Number($('leaveDays').value),note:$('leaveNote').value.trim()});saveData();e.target.reset();$('leaveDate').value=new Date().toISOString().slice(0,10);toast('有給履歴を登録しました')};
function deleteLeave(id){if(!confirm('この有給履歴を削除しますか？'))return;data.leaves=data.leaves.filter(l=>l.id!==id);saveData();toast('履歴を削除しました')}
function renderLeave(){const opts=activeEmployees().map(e=>`<option value="${e.id}">${esc(e.employeeNo)} ${esc(e.name)}</option>`).join('');$('leaveEmployee').innerHTML='<option value="">社員を選択</option>'+opts;$('leaveHistoryFilter').innerHTML='<option value="">全社員</option>'+data.employees.map(e=>`<option value="${e.id}">${esc(e.name)}</option>`).join('');$('leaveSummaryRows').innerHTML=activeEmployees().length?activeEmployees().map(e=>{const ls=data.leaves.filter(l=>l.employeeId===e.id),g=ls.filter(l=>l.type!=='take').reduce((n,l)=>n+Number(l.days),0),t=ls.filter(l=>l.type==='take').reduce((n,l)=>n+Number(l.days),0);return`<tr><td>${esc(e.name)}</td><td>${g}日</td><td>${t}日</td><td><b>${(g-t).toFixed(1).replace('.0','')}日</b></td></tr>`}).join(''):'<tr><td class="empty-cell" colspan="4">社員が登録されていません</td></tr>';renderLeaveHistory()}
function renderLeaveHistory(){const filter=$('leaveHistoryFilter').value,list=[...data.leaves].filter(l=>!filter||l.employeeId===filter).sort((a,b)=>b.date.localeCompare(a.date));$('leaveHistoryRows').innerHTML=list.length?list.map(l=>{const e=data.employees.find(x=>x.id===l.employeeId);return`<tr><td>${fmt(l.date)}</td><td>${esc(e?.name||'削除済み')}</td><td>${l.type==='grant'?'付与':l.type==='take'?'取得':'調整'}</td><td>${l.type==='take'?'-':'+'}${l.days}日</td><td>${esc(l.note||'-')}</td><td><button class="icon-btn" onclick="deleteLeave('${l.id}')">削除</button></td></tr>`}).join(''):'<tr><td class="empty-cell" colspan="6">履歴はありません</td></tr>'}$('leaveHistoryFilter').onchange=renderLeaveHistory;
$('retireForm').onsubmit=e=>{e.preventDefault();const emp=data.employees.find(x=>x.id===$('retireEmployee').value);if(!emp)return;if(!confirm(`${emp.name}さんを退職者として登録しますか？`))return;emp.retireDate=$('retireDate').value;emp.retireReason=$('retireReason').value;emp.retireNote=$('retireNote').value.trim();saveData();e.target.reset();showPage('retirees');toast('退職処理を完了しました')};
function renderRetire(){const opts=activeEmployees().map(e=>`<option value="${e.id}">${esc(e.employeeNo)} ${esc(e.name)}</option>`).join('');$('retireEmployee').innerHTML='<option value="">社員を選択</option>'+opts;const q=$('retireeSearch').value.toLowerCase(),list=data.employees.filter(e=>e.retireDate&&(!q||[e.name,e.kana,e.employeeNo].some(v=>(v||'').toLowerCase().includes(q))));$('retireeRows').innerHTML=list.length?list.map(e=>`<tr><td>${esc(e.employeeNo)}</td><td><b>${esc(e.name)}</b></td><td>${esc(e.department||'-')}</td><td>${fmt(e.hireDate)}</td><td>${fmt(e.retireDate)}</td><td><span class="badge retired">${esc(e.retireReason)}</span></td><td><button class="icon-btn" onclick="selectLedger('${e.id}')">名簿</button> <button class="icon-btn" onclick="restoreEmployee('${e.id}')">在籍に戻す</button></td></tr>`).join(''):'<tr><td class="empty-cell" colspan="7">退職者はいません</td></tr>'}$('retireeSearch').oninput=renderRetire;
function selectLedger(id){$('ledgerEmployee').value=id;renderLedger();showPage('ledger')}
function renderLedger(){const select=$('ledgerEmployee');const current=select.value;select.innerHTML=data.employees.map(e=>`<option value="${e.id}">${esc(e.employeeNo)} ${esc(e.name)}</option>`).join('');if(current&&data.employees.some(e=>e.id===current))select.value=current;const e=data.employees.find(x=>x.id===select.value)||data.employees[0];$('ledgerSheet').innerHTML=e?`<h2>労働者名簿</h2><table class="ledger-table"><tr><th>氏名</th><td>${esc(e.name)}</td><th>生年月日</th><td>${fmt(e.birthDate)}</td></tr><tr><th>氏名（フリガナ）</th><td>${esc(e.kana||'-')}</td><th>性別</th><td>${esc(e.gender||'-')}</td></tr><tr><th>住所</th><td colspan="3">〒${esc(e.postalCode||'-')}　${esc(e.address||'-')}</td></tr><tr><th>雇入年月日</th><td>${fmt(e.hireDate)}</td><th>従事する業務</th><td>${esc([e.department,e.position].filter(Boolean).join(' / ')||'-')}</td></tr><tr><th>雇用形態</th><td>${esc(e.employmentType)}</td><th>社員番号</th><td>${esc(e.employeeNo)}</td></tr><tr><th>退職年月日</th><td>${fmt(e.retireDate)}</td><th>退職事由</th><td>${esc(e.retireReason||'-')}</td></tr><tr><th>電話番号</th><td>${esc(e.phone||'-')}</td><th>備考</th><td>${esc(e.notes||'-')}</td></tr></table><p style="margin-top:28px">作成日：${new Intl.DateTimeFormat('ja-JP').format(new Date())}</p>`:'<div class="empty">社員を登録すると労働者名簿を表示できます</div>'}$('ledgerEmployee').onchange=renderLedger;$('printLedger').onclick=()=>window.print();
function renderSelectDefaults(){if(!$('leaveDate').value)$('leaveDate').value=new Date().toISOString().slice(0,10);if(!$('retireDate').value)$('retireDate').value=new Date().toISOString().slice(0,10)}
function renderAll(){renderDashboard();renderEmployees();renderLeave();renderRetire();renderLedger();renderSelectDefaults()}
$('exportData').onclick=()=>{const blob=new Blob([JSON.stringify({...data,exportedAt:new Date().toISOString()},null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`人事管理バックアップ_${new Date().toISOString().slice(0,10)}.json`;a.click();URL.revokeObjectURL(a.href);toast('バックアップを書き出しました')};
$('importData').onchange=async e=>{const file=e.target.files[0];if(!file)return;try{const parsed=JSON.parse(await file.text());if(!Array.isArray(parsed.employees)||!Array.isArray(parsed.leaves))throw Error();if(!confirm('現在のデータをバックアップ内容で置き換えますか？'))return;data={employees:parsed.employees,leaves:parsed.leaves};saveData();toast('データを復元しました')}catch{alert('正しいバックアップファイルではありません')}e.target.value=''};
$('clearData').onclick=()=>{if(!confirm('本当に全データを削除しますか？'))return;if(!confirm('この操作は元に戻せません。削除を実行しますか？'))return;data={employees:[],leaves:[]};saveData();resetEmployeeForm();toast('全データを削除しました')};
renderAll();
